name: Eleventy Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Build Using node.ks
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Packages
        run:  npm install
      - name: Build
        run:  npm run build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}